.github/workflows/lint-format.yml, package.json
Lint & Format 을 작업한 후에, 해당 작업 내용을 적용
=> chore: Modify Lint and Format Github actions

.github/workflows/lint-format.yml, .github/workflows/run-test.yml, package.json
dev, main 브랜치에 PR 생성시, 테스트 진행 액션 추가
=> chore: Create run-test.yml

.github/workflows/deploy-to-aws-ec2.yml
- main 브랜치에 push 작업이 일어나면, 키 값에 따른 EC2 인스턴스에 접근해서 새롭게 실행하도록 액션 추가
- #16 
resolve #16
=> chore: create deploy-to-aws-ec2.yml

.github/workflows/deploy-to-aws-ec2.yml
- ssh 접속에 문제가 있어서 다른 방법으로 시도합니다..
=> chore: update deploy-to-aws-ec2.yml

.github/workflows/deploy-to-aws-ec2.yml
- 새로운 프로세스를 생성하고 다시 재실행하는 방식이 잘못되어서, 재실행을 먼저 재시도하고 없으면 실행하는 방식으로 변경하였습니다.
=> chore: update pm2 script in deploy-to-aws-ec2.yml

eslint.config.mjs, src/app/pages/travel-traveler-page.tsx, src/components/travel/traveler/TravelerAddDays.tsx, src/components/travel/traveler/TravelerScheduleConfirm.tsx, src/components/travel/traveler/TravelerTravelArrange.tsx, src/components/travel/traveler/TravelerTravelReview.tsx
=> fix: apply changes

src/app/globals.css, src/app/layout.tsx
- 모바일 환경에서 수직 스크롤시 발생하던 오류 수정
- iOS safe area 부분 테마 설정
- #28
=> fix: Issue with vertical scroll in traveler mode on mobile environment 

.gitignore, eslint.config.mjs, package-lock.json, package.json, src/app/layout.tsx, src/providers/TanStackQueryProvider.tsx
- 프로젝트에 `React-Query` 추가
> [!NOTE]
> 추가 작업이 필요하면 브랜치 생성 후 작업하여 PR 올려주세요.
=> chore: Add React Query

src/features/tour-spot/tour-spot.api.ts, src/features/tour-spot/tour-spot.dto.ts, src/features/tour-spot/tour-spot.hook.ts, src/features/trip/trip.api.ts, src/features/trip/trip.dto.ts, src/features/trip/trip.hook.ts, src/features/trip/trip.type.ts
- tour-spot, trip 도메인 API 호출을 위한 관련된 작업 진행했습니다.
=> feat: add tour-spot, trip api

src/features/tour-spot/index.ts, src/features/trip/index.ts
=> fix: add missing export in index files

src/app/globals.css, src/app/layout.tsx, src/components/NavigationBar.tsx, src/components/travel/ContentsCard.tsx
- 모바일 환경에서 내비게이션 바 크기 수정 작업을 진행했습니다.
=> fix: resize navigationbar

src/app/globals.css, src/app/layout.tsx, src/app/pages/travel-auto-page.tsx, src/components/NavigationBar.tsx, src/components/travel/ContentsCard.tsx, src/components/travel/DetailCard.tsx, src/components/travel/Loading.tsx, src/components/travel/PurpleBackground.tsx, src/providers/AuthProvider.tsx
=> fix: Fixed travel-auto page layout

src/components/travel/traveler/TravelerAddDays.tsx, src/features/trip/trip.slice.ts
-`#5-3`, `#5-4` 레이아웃이 변경되었습니다.
- 여행, 활동을 제거하기 위한 액션들을 추가했습니다.
=> feat: add actions to remove item (tour, activity)

src/app/pages/my-page.tsx, src/app/pages/travel-traveler-page.tsx, src/components/LoadingCard.tsx, src/components/NavigationBar.tsx, src/components/TravelList.tsx, src/components/travel/ContentsCard.tsx, src/components/travel/DetailCard.tsx, src/components/travel/traveler/TravelerActivityRecommendation.tsx, src/components/travel/traveler/TravelerActivitySelection.tsx, src/components/travel/traveler/TravelerAddDays.tsx, src/components/travel/traveler/TravelerLocationConfirm.tsx, src/components/travel/traveler/TravelerLocationSearch.tsx, src/components/travel/traveler/TravelerScheduleConfirm.tsx, src/components/travel/traveler/TravelerScheduleSelection.tsx, src/components/travel/traveler/TravelerTravelArrange.tsx, src/features/trip/trip.slice.ts
- 전반적인 레이아웃 변경 작업이 추가되었습니다.
- 여행자 모드에서 이전 화면으로 이동하는 액션이 추가되었습니다.
- 여행, 활동 삭제 기능을 추가했습니다.
=> fix: modify layout, add move to prev page action in traveler-mode

src/components/travel/DetailCard.tsx, src/features/trip/trip.slice.ts
- 여행 추가시 여행 일자 오류를 수정했습니다.
- `addTour` 액션에 tourInfo.endTime 변경하는 로직을 추가
- `removeTour` 액션 수정
=> fix: resolve errors when creating tours when using the fillActivities function, modify addTour function and modify remove function

src/app/pages/my-page.tsx, src/app/pages/profile-edit-page.tsx, src/app/pages/travel-auto-page.tsx, src/app/pages/travel-page.tsx, src/components/TravelLog.tsx, src/components/profile/EditPasswordSection.tsx, src/components/profile/EditProfileSection.tsx, src/components/travel/DetailCard.tsx, src/components/travel/Loading.tsx, src/components/travel/traveler/TravelerActivityRecommendation.tsx, src/features/member/member.api.ts, src/features/member/member.hook.ts, src/providers/AuthProvider.tsx
알아서 해줘 모드 로직 수정 및 AuthProvider reissue 동작 수정
=> feat: Modified some logic

src/app/pages/travel-auto-page.tsx, src/app/pages/travel-page.tsx, src/app/pages/travel-traveler-page.tsx, src/components/DropBox.tsx, src/components/travel/DetailCard.tsx, src/components/travel/Loading.tsx, src/components/travel/traveler/TravelerActivityRecommendation.tsx, src/components/travel/traveler/TravelerActivitySelection.tsx, src/components/travel/traveler/TravelerAddDays.tsx, src/components/travel/traveler/TravelerLocationSearch.tsx, src/components/travel/traveler/TravelerScheduleConfirm.tsx, src/components/travel/traveler/TravelerTravelArrange.tsx, src/features/trip/trip.api.ts, src/features/trip/trip.dto.ts, src/features/trip/trip.slice.ts, src/providers/AuthProvider.tsx, src/providers/ToastProvider.tsx
=> feat: doneeeeeeeeeeeeee

src/components/profile/EditPasswordSection.tsx, src/components/profile/EditProfileSection.tsx, src/components/travel/traveler/TravelerScheduleConfirm.tsx
-  iPhone mini, se 에서 보이는 화면에서 일부 UI가 이상하게 보이는 부분을 수정했습니다.
- 여행 추가 후에 성공 이후에 알 수 없는 이유로 인해 화면이 다음으로 넘어가지 않던 문제를 수정했습니다.
=> fix: resolve issues

package-lock.json, package.json, src/components/profile/EditPasswordSection.tsx, src/components/profile/EditProfileSection.tsx, src/components/travel/traveler/TravelerScheduleConfirm.tsx
- 아이폰 미니, SE에서 UI 일부 오류 수정
- 여행 생성시 오류 처리
=> release: release v1.1.1 to main

src/components/profile/EditPasswordSection.tsx
- 아이폰 미니, SE에서 비밀번호 수정에서 UI가 이상해지는 문제를 수정했습니다.
=> fix: resolve ui issue

package-lock.json, package.json, src/components/profile/EditPasswordSection.tsx
- 아이폰 미니, SE에서 비밀번호 수정에서 UI가 이상해지는 문제를 수정했습니다.
=> release: v1.1.2

src/components/profile/EditPasswordSection.tsx
아이폰 미니, SE 기준 비밀번호 변경 UI 에러 해결
=> fix: Fixed password UI

package-lock.json, package.json, src/components/profile/EditPasswordSection.tsx
=> release: v1.1.3
